pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp *.html public/
    - cp *.svg public/
    - cp places.js public/
    - cp robots.txt public/
    - cp -r open_meteo public/
    - cp -r astro_score public/
    - cp -r pure_math public/
    - cp -r light_pollution public/
    - cp -r google_news_url public/
    - cp -r bigdatacloud public/
  artifacts:
    paths:
      - public
  only:
    - main
    - master
