pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp *.html public/
    - cp *.svg public/
    - cp robots.txt public/
    - cp -r open_meteo public/
    - cp -r google_news_url public/
  artifacts:
    paths:
      - public
  only:
    - main
    - master
